// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using DqccomicsMobileapiService.Models;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace DqccomicsMobileapiService.Models
{
    public partial class ApiBooking
    {
        private string _city;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string City
        {
            get { return this._city; }
            set { this._city = value; }
        }
        
        private string _country;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Country
        {
            get { return this._country; }
            set { this._country = value; }
        }
        
        private string _customerId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string CustomerId
        {
            get { return this._customerId; }
            set { this._customerId = value; }
        }
        
        private double? _customerRating;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? CustomerRating
        {
            get { return this._customerRating; }
            set { this._customerRating = value; }
        }
        
        private string _description;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Description
        {
            get { return this._description; }
            set { this._description = value; }
        }
        
        private DateTimeOffset? _endTime;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? EndTime
        {
            get { return this._endTime; }
            set { this._endTime = value; }
        }
        
        private IList<ApiHeroBasic> _heroes;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<ApiHeroBasic> Heroes
        {
            get { return this._heroes; }
            set { this._heroes = value; }
        }
        
        private int? _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private string _location;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Location
        {
            get { return this._location; }
            set { this._location = value; }
        }
        
        private DateTimeOffset? _startTime;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? StartTime
        {
            get { return this._startTime; }
            set { this._startTime = value; }
        }
        
        private string _status;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Status
        {
            get { return this._status; }
            set { this._status = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ApiBooking class.
        /// </summary>
        public ApiBooking()
        {
            this.Heroes = new LazyList<ApiHeroBasic>();
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken cityValue = inputObject["City"];
                if (cityValue != null && cityValue.Type != JTokenType.Null)
                {
                    this.City = ((string)cityValue);
                }
                JToken countryValue = inputObject["Country"];
                if (countryValue != null && countryValue.Type != JTokenType.Null)
                {
                    this.Country = ((string)countryValue);
                }
                JToken customerIdValue = inputObject["CustomerId"];
                if (customerIdValue != null && customerIdValue.Type != JTokenType.Null)
                {
                    this.CustomerId = ((string)customerIdValue);
                }
                JToken customerRatingValue = inputObject["CustomerRating"];
                if (customerRatingValue != null && customerRatingValue.Type != JTokenType.Null)
                {
                    this.CustomerRating = ((double)customerRatingValue);
                }
                JToken descriptionValue = inputObject["Description"];
                if (descriptionValue != null && descriptionValue.Type != JTokenType.Null)
                {
                    this.Description = ((string)descriptionValue);
                }
                JToken endTimeValue = inputObject["EndTime"];
                if (endTimeValue != null && endTimeValue.Type != JTokenType.Null)
                {
                    this.EndTime = ((DateTimeOffset)endTimeValue);
                }
                JToken heroesSequence = ((JToken)inputObject["Heroes"]);
                if (heroesSequence != null && heroesSequence.Type != JTokenType.Null)
                {
                    foreach (JToken heroesValue in ((JArray)heroesSequence))
                    {
                        ApiHeroBasic apiHeroBasic = new ApiHeroBasic();
                        apiHeroBasic.DeserializeJson(heroesValue);
                        this.Heroes.Add(apiHeroBasic);
                    }
                }
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((int)idValue);
                }
                JToken locationValue = inputObject["Location"];
                if (locationValue != null && locationValue.Type != JTokenType.Null)
                {
                    this.Location = ((string)locationValue);
                }
                JToken startTimeValue = inputObject["StartTime"];
                if (startTimeValue != null && startTimeValue.Type != JTokenType.Null)
                {
                    this.StartTime = ((DateTimeOffset)startTimeValue);
                }
                JToken statusValue = inputObject["Status"];
                if (statusValue != null && statusValue.Type != JTokenType.Null)
                {
                    this.Status = ((string)statusValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type ApiBooking
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.City != null)
            {
                outputObject["City"] = this.City;
            }
            if (this.Country != null)
            {
                outputObject["Country"] = this.Country;
            }
            if (this.CustomerId != null)
            {
                outputObject["CustomerId"] = this.CustomerId;
            }
            if (this.CustomerRating != null)
            {
                outputObject["CustomerRating"] = this.CustomerRating.Value;
            }
            if (this.Description != null)
            {
                outputObject["Description"] = this.Description;
            }
            if (this.EndTime != null)
            {
                outputObject["EndTime"] = this.EndTime.Value;
            }
            JArray heroesSequence = null;
            if (this.Heroes != null)
            {
                if (this.Heroes is ILazyCollection<ApiHeroBasic> == false || ((ILazyCollection<ApiHeroBasic>)this.Heroes).IsInitialized)
                {
                    heroesSequence = new JArray();
                    outputObject["Heroes"] = heroesSequence;
                    foreach (ApiHeroBasic heroesItem in this.Heroes)
                    {
                        if (heroesItem != null)
                        {
                            heroesSequence.Add(heroesItem.SerializeJson(null));
                        }
                    }
                }
            }
            if (this.Id != null)
            {
                outputObject["Id"] = this.Id.Value;
            }
            if (this.Location != null)
            {
                outputObject["Location"] = this.Location;
            }
            if (this.StartTime != null)
            {
                outputObject["StartTime"] = this.StartTime.Value;
            }
            if (this.Status != null)
            {
                outputObject["Status"] = this.Status;
            }
            return outputObject;
        }
    }
}
