// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using DqccomicsMobileapiService;
using DqccomicsMobileapiService.Models;
using Microsoft.Rest;

namespace DqccomicsMobileapiService
{
    public static partial class BookingsExtensions
    {
        /// <param name='operations'>
        /// Reference to the DqccomicsMobileapiService.IBookings.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static ApiBooking DeleteBooking(this IBookings operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IBookings)s).DeleteBookingAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the DqccomicsMobileapiService.IBookings.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<ApiBooking> DeleteBookingAsync(this IBookings operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<DqccomicsMobileapiService.Models.ApiBooking> result = await operations.DeleteBookingWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the DqccomicsMobileapiService.IBookings.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static ApiBooking GetBooking(this IBookings operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IBookings)s).GetBookingAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the DqccomicsMobileapiService.IBookings.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<ApiBooking> GetBookingAsync(this IBookings operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<DqccomicsMobileapiService.Models.ApiBooking> result = await operations.GetBookingWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the DqccomicsMobileapiService.IBookings.
        /// </param>
        public static IList<ApiBooking> GetBookings(this IBookings operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IBookings)s).GetBookingsAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the DqccomicsMobileapiService.IBookings.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<ApiBooking>> GetBookingsAsync(this IBookings operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<DqccomicsMobileapiService.Models.ApiBooking>> result = await operations.GetBookingsWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the DqccomicsMobileapiService.IBookings.
        /// </param>
        /// <param name='booking'>
        /// Required.
        /// </param>
        public static ApiBooking PostBooking(this IBookings operations, ApiBooking booking)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IBookings)s).PostBookingAsync(booking);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the DqccomicsMobileapiService.IBookings.
        /// </param>
        /// <param name='booking'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<ApiBooking> PostBookingAsync(this IBookings operations, ApiBooking booking, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<DqccomicsMobileapiService.Models.ApiBooking> result = await operations.PostBookingWithOperationResponseAsync(booking, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the DqccomicsMobileapiService.IBookings.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='rating'>
        /// Required.
        /// </param>
        public static ApiBooking PostBookingRatings(this IBookings operations, int id, ApiBookingRating rating)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IBookings)s).PostBookingRatingsAsync(id, rating);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the DqccomicsMobileapiService.IBookings.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='rating'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<ApiBooking> PostBookingRatingsAsync(this IBookings operations, int id, ApiBookingRating rating, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<DqccomicsMobileapiService.Models.ApiBooking> result = await operations.PostBookingRatingsWithOperationResponseAsync(id, rating, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the DqccomicsMobileapiService.IBookings.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='booking'>
        /// Required.
        /// </param>
        public static object PutBooking(this IBookings operations, int id, ApiBooking booking)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IBookings)s).PutBookingAsync(id, booking);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the DqccomicsMobileapiService.IBookings.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='booking'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> PutBookingAsync(this IBookings operations, int id, ApiBooking booking, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.PutBookingWithOperationResponseAsync(id, booking, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
